# codebasics lecture 1

In [10]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a[0])
print(a[3])


[1 2 3 4]
1
4


In [27]:
l=range(0,16) # makes an array from 0 to a certain number 
print(l)
l[12]
print(len(l))

range(0, 16)
16


In [38]:
import numpy as np
a=np.arange(16)
print(a)
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)
print(a.nbytes)
print(a.dtype)
print(a.shape)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
16
4
64
int32
(16,)
1
64


In [42]:
#we can do all operations on numpy
import numpy as np
a=np.arange(25)
b=np.arange(26,51)
print(a+b)
print(a*b)
print(a-b)
print((a+b)-(a-b))

[26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72
 74]
[   0   27   56   87  120  155  192  231  272  315  360  407  456  507
  560  615  672  731  792  855  920  987 1056 1127 1200]
[-26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26 -26
 -26 -26 -26 -26 -26 -26 -26]
[ 52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86
  88  90  92  94  96  98 100]


# codebasics lecture 2

In [54]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.dtype)
print(a.nbytes)
print(a.size*a.itemsize)

[[1 2]
 [3 4]
 [5 6]]
2
4
6
int32
24
24


In [66]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)
a=np.array([[1,2],[3,4],[5,6]],dtype=float)
print(a.itemsize)
print(a)
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(a.itemsize)
print(a)
a=np.array([[1,2],[3,4],[5,6]],dtype='int64')
print(a.itemsize)
print(a)

(3, 2)
8
[[1. 2.]
 [3. 4.]
 [5. 6.]]
16
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]
8
[[1 2]
 [3 4]
 [5 6]]


In [69]:
import numpy as np
a=np.zeros((2,4))
print(a)
b=np.ones((2,4))
print(b)
a=np.zeros((2,4),dtype='int64')
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]]


In [71]:
a=range(10)
b=range(5,7)
print(a,b)
print(a[3],b[0])

range(0, 10) range(5, 7)
3 5


In [78]:
a=np.arange(4,10)
print(a)
a[1:3]


[4 5 6 7 8 9]


array([5, 6])

In [82]:
a=np.arange(0,10,3)
print(a)
a=np.arange(10,100,5)
print(a)

[0 3 6 9]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [4]:
import numpy as np
a=np.linspace(0,10,3)
print(a)
a=np.linspace(1,5,10)
print(a)

[ 0.  5. 10.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [11]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
print(a.reshape(4,2))
print(a)
print(a.ravel())
print(a)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.min())
print(a.max())
print(a.sum())
print(a.min(axis=0))
print(a.max(axis=1))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))

1
8
36
[1 2 3 4]
[4 8]
[10 26]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
2.29128784747792


In [17]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[9,10,11,12],[13,14,15,16]])
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[[10 12 14 16]
 [18 20 22 24]]
[[  9  20  33  48]
 [ 65  84 105 128]]
[[-8 -8 -8 -8]
 [-8 -8 -8 -8]]
[[0.11111111 0.2        0.27272727 0.33333333]
 [0.38461538 0.42857143 0.46666667 0.5       ]]


In [18]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
print(a.dot(b))

[[13 16]
 [29 36]]


# codebasics lecture 3

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1])
print(a[3:8])
print(a[3:-3])
print(a[:-4])


2
[4 5 6 7 8]
[4 5 6 7]
[1 2 3 4 5 6]


In [6]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[2,3])
print(a[0,1])
print(a[0:2,0:2])
print(a[1][1:4])
print(a[-1])
print(a[-1,:2])


12
2
[[1 2]
 [5 6]]
[6 7 8]
[ 9 10 11 12]
[ 9 10]


In [16]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for row in a:
    print(row)

for row in a:
    for i in row:
        print(i)

for row in a:
    for i in row:
        print(i, end =" ")

b=a.flat
print(b)

for cell in a.flat:
    print(cell,end=" ")



[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12
1 2 3 4 5 6 7 8 9 10 11 12 <numpy.flatiter object at 0x0000020CF1615130>
1 2 3 4 5 6 7 8 9 10 11 12 

In [32]:
import numpy as np
a=np.arange(1,13).reshape(4,3)
b=np.arange(13,25).reshape(4,3)
c=np.vstack((a,b))
d=np.hstack((a,b))
print(c)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
[[ 1  2  3 13 14 15]
 [ 4  5  6 16 17 18]
 [ 7  8  9 19 20 21]
 [10 11 12 22 23 24]]


In [28]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
b=np.hsplit(a,2)
c=np.vsplit(a,3)
print(b)
print(c)
print(b[0])
print(b[1])
print(a[0])
print(a[1])

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[1 2 3 4]
[5 6 7 8]


In [44]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)
b=a>4
print(b)
print(a[b])
a[b]=-1;
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


# codebasics lecture 4