In [1]:
import numpy as np

# The basics

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
#data type
print(a.dtype)
print(b.dtype)

int32
float64


In [10]:
# dimension
print(a.ndim)
print(b.ndim)

1
2


In [11]:
#shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [13]:
# change datatype
a=np.array([1,2,3],dtype="float64")
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype="int64")
print(a.dtype)
print(b.dtype)

float64
int64


In [14]:
a=np.array([1,2,3])
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [17]:
#size
print(a.size)
print(b.size)
print(a.itemsize)
print(b.itemsize)
print(a.size*a.itemsize)
print(a.nbytes)
print(b.size*b.itemsize)
print(b.nbytes)

3
6
4
8
12
12
48
48


### accessing and changing specific elements of columns,rows

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
#a[r][c] or a[r,c]   r=row,c=column
print(a[1,3])
print(a[-1,:]) # get specific row
print(a[0]) # get specific row
print(a[:,2]) # get specific column
print(a[1:,2:4]) # get ranged elements

11
[ 8  9 10 11 12 13 14]
[ 3 10]
[[10 11]]


In [24]:
# step size  [start:end:gap]
print(a[1,0:5:2])
print(a[0,0:6:3])

[ 8 10 12]
[1 4]


In [27]:
# changing elements
print(a)
a[1,4]=100
print(a)
a[1,:]=[7,6,5,4,3,2,1]
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11 100  13  14]]
[[  1   2   3   4   5   6   7]
 [  8   9  10  11 100  13  14]]
[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


In [29]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
print(b.ndim)
print(b.shape)
print(b[:,1,1])
print(b[0,1,1])
b[0,0,:]=[9,9]
print(b)

3
(2, 2, 2)
[4 8]
4
[[[9 9]
  [3 4]]

 [[5 6]
  [7 8]]]


### initializing different kind of arrays

In [38]:
# zeros matrix
a=np.zeros(4)
b=np.zeros((2,5))
c=np.zeros((2,3,2))
print(a)
print(b)
print(c)
print(c.dtype)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
float64


In [41]:
#ones matrix
a=np.ones(4)
b=np.ones((3,4))
c=np.ones((3,2,3),dtype="int")
print(a)
print(b)
print(c)


[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [44]:
# any other number
d=np.full((4,4),3)
print(d)
e=np.full((3,2),23)
print(e)


[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[23 23]
 [23 23]
 [23 23]]


In [46]:
# take shape of another array and make it full with other number
k=np.full(d.shape,67)
print(k)
k=np.full_like(d,12)
print(k)

[[67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [48]:
#random numbers between 0 to 1
a=np.random.rand(5,5)
print(a)
b=np.random.rand(2,3)
print(b)

[[0.29023232 0.15081012 0.03094384 0.09770685 0.63073758]
 [0.16791302 0.01476077 0.46400331 0.3193827  0.21208958]
 [0.14739013 0.79295585 0.62012017 0.23003568 0.56206471]
 [0.91466439 0.50848147 0.49849901 0.08592665 0.58612637]
 [0.47434327 0.90445045 0.75545759 0.25606826 0.86049944]]
[[0.06527734 0.81275667 0.48298559]
 [0.70940081 0.63892696 0.37288307]]


In [50]:
# random numbers with a particular shape
k=np.random.random_sample(a.shape)
print(k)
l=np.random.random_sample(b.shape)
print(l)

[[0.54027739 0.9927966  0.29629885 0.50805332 0.7034816 ]
 [0.02685073 0.07518169 0.6013451  0.97552691 0.31059548]
 [0.38435039 0.06978992 0.6870411  0.45395347 0.09424257]
 [0.38033483 0.08769284 0.93085869 0.1491562  0.5705746 ]
 [0.93358832 0.94421759 0.28124361 0.55573689 0.56853139]]
[[0.22640572 0.63678287 0.29408127]
 [0.0968836  0.49796337 0.2475376 ]]


In [53]:
# random numbers between particular integers
f=np.random.randint(3,10,size=(7,4))  # int between 3,10
print(f)
t=np.random.randint(5,size=(24))   # int from 0 to 5
print(t)
t=np.random.randint(-8,5,size=(24))   # int from 0 to 5
print(t)

[[3 9 6 8]
 [7 5 3 8]
 [3 6 5 9]
 [9 3 7 5]
 [4 8 7 4]
 [4 6 6 3]
 [8 5 7 5]]
[2 0 2 3 4 0 4 4 1 3 3 1 2 1 2 4 4 3 3 3 3 3 3 0]
[-8 -6 -8 -7  4 -7 -7 -4 -3 -4  4  2  3 -6 -2  3 -2  4  3  3  2 -5 -5 -2]


In [58]:
# identity matrix
a=np.identity(4,dtype="int")
print(a)
b=np.identity(5)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [64]:
# repeat of an array
a=np.array([[2,3,4,5]])
b=np.repeat(a,4,axis=0)
print(b)

[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]


## exercise print the given figure

In [66]:
a=np.ones((5,5))
b=np.zeros((3,3))
b[1,1]=9
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## copying a array

In [71]:
a=np.array([1,2,3,4])
b=a
print(b)
b[2]=99
print(a)
# why a change, it should not be changed
a=np.array([1,2,3,4])
b=a.copy()
print(b)
b[2]=99
print(a)
# a did not change

[1 2 3 4]
[ 1  2 99  4]
[1 2 3 4]
[1 2 3 4]


## mathematics

In [95]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [96]:
a+2

array([3, 4, 5, 6, 7])

In [97]:
a-2

array([-1,  0,  1,  2,  3])

In [98]:
a*2

array([ 2,  4,  6,  8, 10])

In [99]:
a**2

array([ 1,  4,  9, 16, 25])

In [100]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [101]:
a

array([1, 2, 3, 4, 5])

In [102]:
a=a+2
print(a)

[3 4 5 6 7]


In [103]:
print(a)

[3 4 5 6 7]


In [104]:
b=np.array([1,2,3,4,5])
c=a+b
print(c)

[ 4  6  8 10 12]


In [105]:
c=a-b
print(c)

[2 2 2 2 2]


In [106]:
c=a*b
print(c)

[ 3  8 15 24 35]


In [107]:
c=a/b
print(c)

[3.         2.         1.66666667 1.5        1.4       ]


In [108]:
print(a)

[3 4 5 6 7]


In [109]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [110]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [112]:
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619,  0.87144798])

## linear algebra

In [113]:
# matrix multiplication
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [116]:
#matrix multiplication
c=np.matmul(a,b)
print(c)
# determinant finding
a=np.array([[1,2],[33,23]])
print(np.linalg.det(a)) # finding determinant

[[6. 6.]
 [6. 6.]]
-43.0


## statistics

In [121]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)
print(stats.max())
print(np.max(stats))
print(stats.max(axis=0))
print(np.max(stats,axis=0))


[[1 2 3]
 [4 5 6]]
6
6
[4 5 6]
[4 5 6]


In [122]:
print(stats.min())
print(np.min(stats))
print(stats.min(axis=0))
print(np.min(stats,axis=1))

1
1
[1 2 3]
[1 4]


In [123]:
print(stats.sum())
print(np.sum(stats))
print(stats.sum(axis=0))
print(np.sum(stats,axis=1))

21
21
[5 7 9]
[ 6 15]


## reorganizing the arrays

In [124]:
before=np.array([[1,2,3,4,5,9],[6,7,8,9,10,87]])
c=before.reshape((3,4))
print(c)

[[ 1  2  3  4]
 [ 5  9  6  7]
 [ 8  9 10 87]]


In [131]:
a=np.arange(12).reshape((3,4))
b=np.arange(12,24).reshape((3,4))
c=np.vstack((a,b,a,a))
d=np.hstack((a,b,b,b,a))
print(c)
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3 12 13 14 15 12 13 14 15 12 13 14 15  0  1  2  3]
 [ 4  5  6  7 16 17 18 19 16 17 18 19 16 17 18 19  4  5  6  7]
 [ 8  9 10 11 20 21 22 23 20 21 22 23 20 21 22 23  8  9 10 11]]


## advanced indexing and boolean masking

In [134]:
a=np.random.randint(0,100,size=(10,10))
print(a)

[[59 75  0 21 95 65 55 51  2 64]
 [34 49 94 33 26 73 72 99 12 86]
 [90 70 81 11 98 22 86 24 56 54]
 [14 79 62 59 89 88 71 53 47  3]
 [42 11 44 88 92 54 17 96 82 70]
 [28  3 48 30 18 44 99 30 71  7]
 [32 75 18 11 36 55 15 97  7 54]
 [26 65 38  9 62 86 93 34 10 24]
 [21 29  9 55 24 54 41 43 21 25]
 [37 38 42 16 82  0 73 70 44 82]]


In [135]:
a>25

array([[ True,  True, False, False,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True, False,  True, False,  True, False,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True, False,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True, False,  True,  True, False,  True,  True,  True,  True,
        False],
       [ True,  True, False, False,  True,  True, False,  True, False,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True, False,
        False],
       [False,  True, False,  True, False,  True,  True,  True, False,
        False],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
         True]])

In [136]:
a[a>25]

array([59, 75, 95, 65, 55, 51, 64, 34, 49, 94, 33, 26, 73, 72, 99, 86, 90,
       70, 81, 98, 86, 56, 54, 79, 62, 59, 89, 88, 71, 53, 47, 42, 44, 88,
       92, 54, 96, 82, 70, 28, 48, 30, 44, 99, 30, 71, 32, 75, 36, 55, 97,
       54, 26, 65, 38, 62, 86, 93, 34, 29, 55, 54, 41, 43, 37, 38, 42, 82,
       73, 70, 44, 82])

In [141]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[[1,2,8]]

array([2, 3, 9])

In [142]:
print(a)

[[59 75  0 21 95 65 55 51  2 64]
 [34 49 94 33 26 73 72 99 12 86]
 [90 70 81 11 98 22 86 24 56 54]
 [14 79 62 59 89 88 71 53 47  3]
 [42 11 44 88 92 54 17 96 82 70]
 [28  3 48 30 18 44 99 30 71  7]
 [32 75 18 11 36 55 15 97  7 54]
 [26 65 38  9 62 86 93 34 10 24]
 [21 29  9 55 24 54 41 43 21 25]
 [37 38 42 16 82  0 73 70 44 82]]


In [143]:
np.any(a>25,axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [144]:
np.all(a>25,axis=1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [145]:
print(a)

[[59 75  0 21 95 65 55 51  2 64]
 [34 49 94 33 26 73 72 99 12 86]
 [90 70 81 11 98 22 86 24 56 54]
 [14 79 62 59 89 88 71 53 47  3]
 [42 11 44 88 92 54 17 96 82 70]
 [28  3 48 30 18 44 99 30 71  7]
 [32 75 18 11 36 55 15 97  7 54]
 [26 65 38  9 62 86 93 34 10 24]
 [21 29  9 55 24 54 41 43 21 25]
 [37 38 42 16 82  0 73 70 44 82]]


In [148]:
((a>25) & (a<40))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False,  True, False, False, False,  True, False,
        False],
       [ True, False, False, False,  True, False, False, False, False,
        False],
       [ True, False,  True, False, False, False, False,  True, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [ True,  True, False, False, False, False, False, False, False,
        False]])

In [149]:
a[((a>25) & (a<40))]

array([34, 33, 26, 28, 30, 30, 32, 36, 26, 38, 34, 29, 37, 38])

In [150]:
~((a>25) & (a<40))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True, False,  True,  True,  True, False,  True,
         True],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [False,  True, False,  True,  True,  True,  True, False,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [151]:
a[~((a>25) & (a<40))]

array([59, 75,  0, 21, 95, 65, 55, 51,  2, 64, 49, 94, 73, 72, 99, 12, 86,
       90, 70, 81, 11, 98, 22, 86, 24, 56, 54, 14, 79, 62, 59, 89, 88, 71,
       53, 47,  3, 42, 11, 44, 88, 92, 54, 17, 96, 82, 70,  3, 48, 18, 44,
       99, 71,  7, 75, 18, 11, 55, 15, 97,  7, 54, 65,  9, 62, 86, 93, 10,
       24, 21,  9, 55, 24, 54, 41, 43, 21, 25, 42, 16, 82,  0, 73, 70, 44,
       82])